windows:
  "2":
    name: server@8889
    command: |
      export MIDDLEMNAN_PORT=8889
      export PATH=$(pwd)/vendor/jruby/bin:$PATH
      jruby --dev -S bundle exec middleman -p $MIDDLEMNAN_PORT

  "7":
    name: test
    command: |
      export PATH=$(pwd)/vendor/jruby/bin:$PATH
      export DOCS_CONTEXT='/'
      export MIDDLEMNAN_PORT=8889
      sleep 5
      jruby --dev -S bundle exec rspec
