jobs:
  test-documentation:
    name: Test Documentation
    run_when:
      'any branch is updated':
        type: branch
        include_match: ^.*$
    context:
      task_defaults:
        max_trials: 1
        traits:
          Pandoc: yes
          ruby-install: yes
        include:
          - cider-ci/task_components/bundle.yml
          - cider-ci/task_components/server.yml
        environment_variables:
          DOCS_CONTEXT: '/'
          DISPLAY: ':{{DISPLAY_PORT}}'
        ports:
          MIDDLEMNAN_PORT:
            min: 8000
            max: 8999
          DISPLAY_PORT:
            min: 9000
            max: 9999

      tasks:
        test:
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                mkdir -p log
                sleep 30
                xvfb-run -a -e log/xvfb.log bundle exec rspec

